### ISSUE TITLE
设置GK热键报错

### ISSUE THREAD

**Issue by lanybass** [einsxiao/GlobalVim#2]
在设置GK键的弹窗中按任意键都报错，确定之后发现没设置成功
```
Traceback (most recent call last):
  File "E:\github\GlobalVim\GeeKey.py", line 1152, in onKeyboardClear
    log.log( lt('Keyboard State Cleared') )
  File "E:\github\GlobalVim\res.py", line 82, in log
    cls.log_func(cont)
  File "E:\github\GlobalVim\GeeKey.py", line 1842, in Log
    self.text.SetValue( "> "+ cont+"\n------------------------------\n"+ori[:6666] )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2: ordinal not in range(128)
```

**Comment by lanybass** [comment]
好吧。。找到问题了。我用的Python2.7 。换成python3就OK了
