### ISSUE TITLE
VIM命令输入不了

### ISSUE THREAD

**Issue by lanybass** [einsxiao/GlobalVim#4]
按了:之后，光标切换到命令提示符上，原文本编辑器失去焦点
  我输入命令之后，按回车就报错
```
Traceback (most recent call last):
  File "E:\github\GlobalVim\GeeKey.py", line 1506, in OnKeyboardEvent
    return self.vim.ProcessKey(Key,EvtType)
  File "E:\github\GlobalVim\Vim.py", line 476, in ProcessKey
    win32gui.SetForegroundWindow(self.indicator.last_win )
pywintypes.error: (1400, 'SetForegroundWindow', '无效的窗口句柄。')

Traceback (most recent call last):
  File "E:\github\GlobalVim\GeeKey.py", line 1632, in OnMouseEvent
    self.vim.indicator.StateReset( )
  File "E:\github\GlobalVim\Vim.py", line 168, in StateReset
    if self.FindFocus() == self.text_input: win32gui.SetForegroundWindow(self.la
st_win)
pywintypes.error: (1400, 'SetForegroundWindow', '无效的窗口句柄。')
```
print看了下，self.last_win也就是self.GetTopWindow() 永远是0

**Comment by lanybass** [comment]
user32.GetGUIThreadInfo(0, byref(self.ui) )
self.ui结构体里的变量全是0

**Comment by lanybass** [comment]
经测试，在python2里GetGUIThreadInfo有效，而python3里全是0，不知道是不是我环境问题。我再检查下

**Comment by einsxiao** [comment]
@lanybass 我没有在win7下面测试过，可能是版本不匹配，python3版本是3.7.3

**Comment by lanybass** [comment]
python3.7.3 64位试了依然0  
换了python3.7.3 32位就行了，解决~
